/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sweng431.lab4.newtonraphson;

import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author yha5009
 */
public class ExtremeFinderMenu extends javax.swing.JFrame {
    
    private HashMap<String, Integer> coefs;
    
    /**
     * Creates new form ExtremeFinderMenu
     */
    public ExtremeFinderMenu() {
        coefs = new HashMap<>();
        initComponents();
        aField.setInputVerifier(new CoefVerifier());
        bField.setInputVerifier(new CoefVerifier());
        cField.setInputVerifier(new CoefVerifier());
        dField.setInputVerifier(new CoefVerifier());
        eField.setInputVerifier(new CoefVerifier());
        fField.setInputVerifier(new CoefVerifier());
        saveEnteredCoefs();
    }
    
    public HashMap<String,Integer> getCoefs() {
        saveEnteredCoefs();
        return coefs;
    }
    
    private void saveEnteredCoefs() {
        try {
            coefs.put("a", Integer.parseInt(aField.getText()));
            coefs.put("b", Integer.parseInt(bField.getText()));
            coefs.put("c", Integer.parseInt(cField.getText()));
            coefs.put("d", Integer.parseInt(dField.getText()));
            coefs.put("e", Integer.parseInt(eField.getText()));
            coefs.put("f", Integer.parseInt(fField.getText()));
        } catch (NumberFormatException e) {
            
        }
    }
    
    private void updateFormualLabel() {
        Integer a = coefs.get("a");
        Integer b = coefs.get("b");
        Integer c = coefs.get("c");
        Integer d = coefs.get("d");
        Integer e = coefs.get("e");
        Integer f = coefs.get("f");
        String str = a+"x^9 + "+ b +"x^7 + "+ c +"x^5 + "+ d +"x^3 + "+ e +"x + "+ f +""; 
        formulaLabel.setText(str);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formulaLabel = new javax.swing.JLabel();
        aField = new javax.swing.JTextField();
        bField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cField = new javax.swing.JTextField();
        dField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        eField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        guessLabel = new javax.swing.JLabel();
        rootLabel = new javax.swing.JLabel();
        maxXLabel = new javax.swing.JLabel();
        maxYLabel = new javax.swing.JLabel();
        searchButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formulaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        formulaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formulaLabel.setText("ax^9 + bx^7 + cx^5 + dx^3 + ex + f");

        aField.setText("-100");
        aField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aFieldKeyReleased(evt);
            }
        });

        bField.setText("100");
        bField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bFieldKeyReleased(evt);
            }
        });

        jLabel2.setText("a");

        jLabel3.setText("b");

        jLabel4.setText("d");

        cField.setText("100");
        cField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cFieldKeyReleased(evt);
            }
        });

        dField.setText("100");
        dField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dFieldKeyReleased(evt);
            }
        });

        jLabel5.setText("c");

        jLabel6.setText("f");

        fField.setText("100");
        fField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fFieldKeyReleased(evt);
            }
        });

        jLabel7.setText("e");

        eField.setText("100");
        eField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                eFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                eFieldKeyTyped(evt);
            }
        });

        jLabel1.setText("Root (x):");

        jLabel8.setText("Maximum/Minimum (x):");

        jLabel9.setText("Maximum/Minimum (y):");

        jLabel10.setText("Guess (x):");

        guessLabel.setText("n/a");

        rootLabel.setText("n/a");

        maxXLabel.setText("n/a");

        maxYLabel.setText("n/a");

        searchButton.setText("SEARCH");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formulaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maxXLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(maxYLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(guessLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                            .addComponent(rootLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formulaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(guessLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(rootLabel))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(maxXLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(maxYLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aFieldKeyPressed
        saveEnteredCoefs();
        updateFormualLabel();
    }//GEN-LAST:event_aFieldKeyPressed

    private void bFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bFieldKeyPressed
        saveEnteredCoefs();
        updateFormualLabel();
    }//GEN-LAST:event_bFieldKeyPressed

    private void cFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cFieldKeyPressed
        saveEnteredCoefs();
        updateFormualLabel();
    }//GEN-LAST:event_cFieldKeyPressed

    private void dFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dFieldKeyPressed
        saveEnteredCoefs();
        updateFormualLabel();
    }//GEN-LAST:event_dFieldKeyPressed

    private void eFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_eFieldKeyTyped

    private void eFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eFieldKeyPressed
        saveEnteredCoefs();
        updateFormualLabel();
    }//GEN-LAST:event_eFieldKeyPressed

    private void fFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fFieldKeyPressed
        saveEnteredCoefs();
        updateFormualLabel();
    }//GEN-LAST:event_fFieldKeyPressed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        Double randomGuess = Math.random()*10000 - 5000;
        guessLabel.setText(randomGuess.toString());
        
        NewtonsMethod.setCoefs(coefs.get("a"), coefs.get("b"), coefs.get("c"),
                coefs.get("d"), coefs.get("e"), coefs.get("f"));
        
        try {
            Double root = NewtonsMethod.findRoot(randomGuess);
            rootLabel.setText(root.toString());
            log(root);
        } catch (Error e) {
            rootLabel.setText("No root found");
        }
        try {
            Double maxX = NewtonsMethod.findMaxima(randomGuess);
            maxXLabel.setText(maxX.toString());
            log(maxX);
            
            Double maxY = NewtonsMethod.f(maxX);
            maxYLabel.setText(maxY.toString());
            log(maxY);
        } catch (Error e) {
            maxXLabel.setText("No max/min found");
            maxYLabel.setText("No max/min found");
        }
        log("\n");
    }//GEN-LAST:event_searchButtonActionPerformed
    
    private void log(Object msg) {
        System.out.println(msg.toString());
    }
    
    private void aFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aFieldKeyReleased
        saveEnteredCoefs();
        updateFormualLabel();
    }//GEN-LAST:event_aFieldKeyReleased

    private void bFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bFieldKeyReleased
        saveEnteredCoefs();
        updateFormualLabel();
    }//GEN-LAST:event_bFieldKeyReleased

    private void cFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cFieldKeyReleased
        saveEnteredCoefs();
        updateFormualLabel();
    }//GEN-LAST:event_cFieldKeyReleased

    private void dFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dFieldKeyReleased
        saveEnteredCoefs();
        updateFormualLabel();
    }//GEN-LAST:event_dFieldKeyReleased

    private void eFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eFieldKeyReleased
        saveEnteredCoefs();
        updateFormualLabel();
    }//GEN-LAST:event_eFieldKeyReleased

    private void fFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fFieldKeyReleased
        saveEnteredCoefs();
        updateFormualLabel();
    }//GEN-LAST:event_fFieldKeyReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ExtremeFinderMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ExtremeFinderMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ExtremeFinderMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ExtremeFinderMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ExtremeFinderMenu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aField;
    private javax.swing.JTextField bField;
    private javax.swing.JTextField cField;
    private javax.swing.JTextField dField;
    private javax.swing.JTextField eField;
    private javax.swing.JTextField fField;
    private javax.swing.JLabel formulaLabel;
    private javax.swing.JLabel guessLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel maxXLabel;
    private javax.swing.JLabel maxYLabel;
    private javax.swing.JLabel rootLabel;
    private javax.swing.JToggleButton searchButton;
    // End of variables declaration//GEN-END:variables
}
